# Generated by Django 5.2.6 on 2025-12-18 09:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_branch_city_alter_clientprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guarantor',
            options={'ordering': ['created_at'], 'verbose_name': 'Guarantor', 'verbose_name_plural': 'Guarantors'},
        ),
        migrations.AlterModelOptions(
            name='nextofkin',
            options={'verbose_name': 'Next of Kin', 'verbose_name_plural': 'Next of Kin'},
        ),
        migrations.AddField(
            model_name='guarantor',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional guarantor email', max_length=254),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='employer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card")], max_length=50),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Guarantor's monthly income", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about guarantor'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional NOK email', max_length=254),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='employer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about next of kin'),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='relationship',
            field=models.CharField(help_text='Relationship to client (e.g., Brother, Friend)', max_length=100),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='client',
            field=models.OneToOneField(limit_choices_to={'user_role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='relationship',
            field=models.CharField(help_text='Relationship to client (e.g., Mother, Spouse)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['client'], name='app_guarant_client__298ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['phone'], name='app_guarant_phone_0b59d0_idx'),
        ),
        migrations.AddIndex(
            model_name='nextofkin',
            index=models.Index(fields=['client'], name='app_nextofk_client__bcf8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='nextofkin',
            index=models.Index(fields=['phone'], name='app_nextofk_phone_028378_idx'),
        ),
    ]
