# Generated by Django 5.2.6 on 2025-12-22 15:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_guarantor_options_alter_nextofkin_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loan',
            name='app_loan_client__89d6d8_idx',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='supporting_document_1',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='supporting_document_2',
        ),
        migrations.AddField(
            model_name='loan',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Annual interest rate percentage for display', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount deducted from disbursement (fees, insurance, etc.)', max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='deduction_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='loan',
            name='duration_value',
            field=models.IntegerField(default=10, help_text='Number of payment periods (e.g., 30 days, 12 weeks, 6 months)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor2_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor2_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor2_phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_interest_rate',
            field=models.DecimalField(decimal_places=4, default=10, help_text='Monthly interest rate used (as decimal, e.g., 0.0500 for 5%)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='net_disbursement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount received by client (principal - deductions)', max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='number_of_installments',
            field=models.IntegerField(default=0, help_text='Total number of payments'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='monthly', help_text='How often the client will make payments', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, help_text='Total interest to be paid (P × r × t)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_repayment',
            field=models.DecimalField(decimal_places=2, help_text='Principal + Total Interest', max_digits=15),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['repayment_frequency'], name='app_loan_repayme_cfc534_idx'),
        ),
    ]
