# Generated by Django 5.2.6 on 2025-12-26 23:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_loan_app_loan_client__89d6d8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='id_card_back',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Back side of ID card', max_length=255, null=True, verbose_name='id_card_back'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='id_card_front',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Front side of ID card', max_length=255, null=True, verbose_name='id_card_front'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card")], max_length=50),
        ),
    ]
