# Generated by Django 5.2.6 on 2025-12-27 12:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transaction_approved_at_transaction_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-application_date']},
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='app_loan_status_39bfb5_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='app_loan_branch__80140b_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='app_loan_next_re_67beae_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='app_loan_disburs_12aba9_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='app_loan_repayme_cfc534_idx',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='days_overdue',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='deduction_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='deduction_reason',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='last_overdue_check',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='net_disbursement',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='notes',
        ),
        migrations.AddField(
            model_name='loan',
            name='duration_months',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration converted to months', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_term',
            field=models.IntegerField(default=0, help_text='Duration in months (for display)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_frequency',
            field=models.CharField(default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_disbursed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='annual_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate as percentage (e.g., 60 for 60%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='collateral_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='collateral_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_disbursed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration_value',
            field=models.IntegerField(help_text='Number of payment periods (days, weeks, or months depending on frequency)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor2_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor2_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor2_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount per installment', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Monthly interest rate as decimal (e.g., 0.05 for 5%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total interest to be paid', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_repayment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount to be repaid (principal + interest)', max_digits=15),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['branch', 'status'], name='app_loan_branch__5fcc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'next_repayment_date'], name='app_loan_status_f28da3_idx'),
        ),
    ]
